# This file was generated by GoReleaser. DO NOT EDIT.
cask "flick" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ce08b9c49e0dd85a5a98beee4cb1651fee062c75de47a27d5df16f28f3b4fe88"
      url "https://github.com/evgfitil/flick/releases/download/v#{version}/flick_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3cb83e5b27b87b866e5ecf4f5768ca0238e34fc3bb1dd522460b3d7305324675"
      url "https://github.com/evgfitil/flick/releases/download/v#{version}/flick_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d41edf635c6c47b0b173e1bd986415c77f86fa6508df74d978159a821645dc92"
      url "https://github.com/evgfitil/flick/releases/download/v#{version}/flick_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "119e399d2e6df77c0699852adb317c77dcf0f71053bad3d92e3bbf66bb756c3f"
      url "https://github.com/evgfitil/flick/releases/download/v#{version}/flick_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flick"
  desc "Claude Code notification plugin for the Kitty terminal"
  homepage "https://github.com/evgfitil/flick"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flick"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flick"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To wire flick into Claude Code, run:
      flick install
    This idempotently registers the hooks in ~/.claude/settings.json and
    prints the kitty.conf remote-control snippet. Undo with:
      flick uninstall
  EOS
end
