# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qx < Formula
  desc "Generate shell commands from natural language using LLM"
  homepage "https://github.com/evgfitil/qx"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evgfitil/qx/releases/download/v0.3.2/qx_darwin_amd64.tar.gz"
      sha256 "82c3033b50ec4d1de1cda82ce175be46773d4b596ec156e4def506b026ba2d22"

      def install
        bin.install "qx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evgfitil/qx/releases/download/v0.3.2/qx_darwin_arm64.tar.gz"
      sha256 "3ec632234741bb5fdbe0963626baf9b6582cee754a3df30f19eb3036d823f705"

      def install
        bin.install "qx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evgfitil/qx/releases/download/v0.3.2/qx_linux_amd64.tar.gz"
      sha256 "185eb3ef6a82559170b9506c3951d03d3faa4de79ffc44710a53a0e3187e9982"
      def install
        bin.install "qx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evgfitil/qx/releases/download/v0.3.2/qx_linux_arm64.tar.gz"
      sha256 "a1c4f3cf5be1452ed05e807f8ed85856048912beb755369e57a72b06d0356cc0"
      def install
        bin.install "qx"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration (Ctrl+G hotkey), add to your shell config:

        # zsh (~/.zshrc)
        source <(qx --shell-integration zsh)

        # bash (~/.bashrc)
        eval "$(qx --shell-integration bash)"
    EOS
  end

  test do
    system "#{bin}/qx", "--help"
  end
end
