# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qx < Formula
  desc "Generate shell commands from natural language using LLM"
  homepage "https://github.com/evgfitil/qx"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evgfitil/qx/releases/download/v0.6.0/qx_darwin_amd64.tar.gz"
      sha256 "785172df0638170cdd1c69135f7676d583bd64c9b2e18009835fa4f1ae2d327d"

      def install
        bin.install "qx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evgfitil/qx/releases/download/v0.6.0/qx_darwin_arm64.tar.gz"
      sha256 "c76f50df0a7bb43ed40b0f73364d8e0c63ccceb2d24ccbd2bd7571fd1c7fa054"

      def install
        bin.install "qx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evgfitil/qx/releases/download/v0.6.0/qx_linux_amd64.tar.gz"
      sha256 "c0ca27e99f2bde5bb804c703feb4386b9fe19a779f320de3cab8d14ca42bd2f3"
      def install
        bin.install "qx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evgfitil/qx/releases/download/v0.6.0/qx_linux_arm64.tar.gz"
      sha256 "7d542ece36fdf67ae7cfa5eba327a81de84f82545e2ce42d57fac074948ee590"
      def install
        bin.install "qx"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration (Ctrl+G hotkey), add to your shell config:

        # zsh (~/.zshrc)
        source <(qx --shell-integration zsh)

        # bash (~/.bashrc)
        eval "$(qx --shell-integration bash)"
    EOS
  end

  test do
    system "#{bin}/qx", "--help"
  end
end
