# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qx < Formula
  desc "Generate shell commands from natural language using LLM"
  homepage "https://github.com/evgfitil/qx"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evgfitil/qx/releases/download/v0.6.1/qx_darwin_amd64.tar.gz"
      sha256 "e07ed74192fef3fa691f2d7805070fa3fa12c96967c78dd941b329e5c3592876"

      def install
        bin.install "qx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evgfitil/qx/releases/download/v0.6.1/qx_darwin_arm64.tar.gz"
      sha256 "f046140bc512309eea7133ae4105e39395fea083e361c4e02ab6fc7c28a6485f"

      def install
        bin.install "qx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evgfitil/qx/releases/download/v0.6.1/qx_linux_amd64.tar.gz"
      sha256 "ff377f473c54bceeb544b5c2c0ef71a5cfccc81f93ca78c9a134bfbbc5486be9"
      def install
        bin.install "qx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evgfitil/qx/releases/download/v0.6.1/qx_linux_arm64.tar.gz"
      sha256 "5900e0ce0125280ebb224df7b2f5853d782a1a7aad97561d7ec01a4fd7979ff1"
      def install
        bin.install "qx"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration (Ctrl+G hotkey), add to your shell config:

        # zsh (~/.zshrc)
        source <(qx --shell-integration zsh)

        # bash (~/.bashrc)
        eval "$(qx --shell-integration bash)"
    EOS
  end

  test do
    system "#{bin}/qx", "--help"
  end
end
