# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revdiff < Formula
  desc "TUI for reviewing diffs, files, and documents with inline annotations (fork of umputun/revdiff, adds arc)"
  homepage "https://github.com/evgfitil/revdiff-releases"
  version "1.4.1-arc"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evgfitil/revdiff-releases/releases/download/v1.4.1-arc/revdiff_1.4.1-arc_darwin_amd64.tar.gz"
      sha256 "6ea1342b4ff5838f5c0d07a91534a92d9ba891548e44ded223c42f99be25e9ae"

      define_method(:install) do
        bin.install "revdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evgfitil/revdiff-releases/releases/download/v1.4.1-arc/revdiff_1.4.1-arc_darwin_arm64.tar.gz"
      sha256 "acba7576690a05cd343bb95378c1e9e49770a00e1942bff88e6d79f3a48e672e"

      define_method(:install) do
        bin.install "revdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evgfitil/revdiff-releases/releases/download/v1.4.1-arc/revdiff_1.4.1-arc_linux_amd64.tar.gz"
      sha256 "81cf6d0db6ccddd240610e6b7b94a4376ec970f1e2c6f579aeb539fc19fae94b"
      define_method(:install) do
        bin.install "revdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evgfitil/revdiff-releases/releases/download/v1.4.1-arc/revdiff_1.4.1-arc_linux_arm64.tar.gz"
      sha256 "e85c90391ce8384d3962bf51e4f0bd19a363963a4638abf68b6a43da0c62d6ea"
      define_method(:install) do
        bin.install "revdiff"
      end
    end
  end
end
