# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revdiff < Formula
  desc "TUI for reviewing diffs, files, and documents with inline annotations (fork of umputun/revdiff, adds arc)"
  homepage "https://github.com/evgfitil/revdiff-releases"
  version "1.13.0-arc"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evgfitil/revdiff-releases/releases/download/v1.13.0-arc/revdiff_1.13.0-arc_darwin_amd64.tar.gz"
      sha256 "d39add2e9847ababea7a7438515c795a2387563dea7b39d7edc32d22bfe15d01"

      define_method(:install) do
        bin.install "revdiff"
        bash_completion.install "completions/revdiff.bash" => "revdiff"
        zsh_completion.install "completions/revdiff.zsh" => "_revdiff"
        fish_completion.install "completions/revdiff.fish" => "revdiff.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evgfitil/revdiff-releases/releases/download/v1.13.0-arc/revdiff_1.13.0-arc_darwin_arm64.tar.gz"
      sha256 "49c23783db1c0a70f005ab0dc3274d0c4db6205c1118bdc4e3e42ae8b53c2184"

      define_method(:install) do
        bin.install "revdiff"
        bash_completion.install "completions/revdiff.bash" => "revdiff"
        zsh_completion.install "completions/revdiff.zsh" => "_revdiff"
        fish_completion.install "completions/revdiff.fish" => "revdiff.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evgfitil/revdiff-releases/releases/download/v1.13.0-arc/revdiff_1.13.0-arc_linux_amd64.tar.gz"
      sha256 "5d94823da7abe07f16c325439b8db192759b25bda57bdede09aa37042e18514a"
      define_method(:install) do
        bin.install "revdiff"
        bash_completion.install "completions/revdiff.bash" => "revdiff"
        zsh_completion.install "completions/revdiff.zsh" => "_revdiff"
        fish_completion.install "completions/revdiff.fish" => "revdiff.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evgfitil/revdiff-releases/releases/download/v1.13.0-arc/revdiff_1.13.0-arc_linux_arm64.tar.gz"
      sha256 "6e6779f6d22acefcdaa612c2ec52bfb59754daa3ac1cd3100f0670bbe5b59b8d"
      define_method(:install) do
        bin.install "revdiff"
        bash_completion.install "completions/revdiff.bash" => "revdiff"
        zsh_completion.install "completions/revdiff.zsh" => "_revdiff"
        fish_completion.install "completions/revdiff.fish" => "revdiff.fish"
      end
    end
  end
end
